# posts/urls.py

from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import PostViewSet, CommentViewSet

# Create a router instance
router = DefaultRouter()

# Register the Post ViewSet - this creates routes like /posts/ and /posts/{pk}/
router.register(r'posts', PostViewSet)

# Register the Comment ViewSet - this creates routes like /comments/ and /comments/{pk}/
router.register(r'comments', CommentViewSet)

urlpatterns = [
    # Include all the routes generated by the router
    path('', include(router.urls)),
]